# Generated by Django 4.2.2 on 2024-01-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Order Confirmed'), (2, 'Order Processed'), (3, 'Order delivered'), (4, 'Order Rejected')], default=0),
        ),
    ]
